// Solo datos, sin links
const invitados = {
  "1":  { "nombre": "Lic. Juan Carlos Maeda Hernández", "pases": 3 },
  "2":  { "nombre": "Sr. Daniel Vásquez y esposa", "pases": 2 },
  "3":  { "nombre": "Sr. Juan Manuel Pico y Familia", "pases": 3 },
  "4":  { "nombre": "Sr. Javier Vásquez y Familia", "pases": 3 },
  "5":  { "nombre": "Lic. Luis López Marroquín y Familia", "pases": 3 },
  "6":  { "nombre": "Ing. Gary Borrayo y esposa", "pases": 2 },
  "7":  { "nombre": "Claudia Rosales", "pases": 4 },
  "8":  { "nombre": "Sra. Yolanda Marroquín e hijos", "pases": 3 },
  "9":  { "nombre": "Sr. Carlos Cruz y Familia", "pases": 4 },
  "10": { "nombre": "Sr. Jorge Manuel Cruz y Familia", "pases": 5 },
  "11": { "nombre": "Sr. Helberth Godoy y Familia", "pases": 5 },
  "12": { "nombre": "Dr. Juan Roberto Morales Castillo", "pases": 1 },
  "13": { "nombre": "Licda. Yani cheverría", "pases": 1 },
  "14": { "nombre": "Dra. María Victoria Morales", "pases": 2 },
  "15": { "nombre": "Sra. Viviam Marisol Escobar Morales y Familia", "pases": 3 },
  "16": { "nombre": "Sra. Leticia Morales Castillo", "pases": 1 },
  "17": { "nombre": "Lic. Estuardo Morales Escobar", "pases": 2 },
  "18": { "nombre": "Lic. Henry Loarca y Familia", "pases": 4 },
  "19": { "nombre": "Sra. Estela Castillo", "pases": 1 },
  "20": { "nombre": "Edwin Quezada", "pases": 2 },
  "21": { "nombre": "Licda. Mariela Meda", "pases": 1 },
  "22": { "nombre": "Sra. Cindy Ávila e hijo", "pases": 2 },
  "23": { "nombre": "Sra. Alejandra del Águila e hija", "pases": 2 },
  "24": { "nombre": "Lic. Ronald Estrada", "pases": 1 },
  "25": { "nombre": "Sr. Diego Li y Familia", "pases": 3 },
  "26": { "nombre": "Sr. Carlos Augusto Maeda García y famiia", "pases": 5 },
  "27": { "nombre": "Sr. Ricardo Sagastume y familia", "pases": 3 },
  "28": { "nombre": "Sr. Diego Lima", "pases": 1 },
  "29": { "nombre": "Sr. Marco Antonio Cruz y Familia", "pases": 4 },
  "30": { "nombre": "Sr. Juan Pablo Zamora y Familia", "pases": 2 },
  "31": { "nombre": "Sr. Jorge Monterroso y familia", "pases": 2 },
  "32": { "nombre": "Sr. Jorge Monterroso y familia", "pases": 4 },
  "33": { "nombre": "Sr. José Fernando Monterroso y familia", "pases": 3 },
  "34": { "nombre": "Sra. María Hernández e hijo", "pases": 2 },
  "35": { "nombre": "Sr. Diego Estrada y esposa", "pases": 2 },
  "36": { "nombre": "Sr. Hugo Estrada y familia", "pases": 4 },
  "37": { "nombre": "Sr. Obelio Betancurt y esposa", "pases": 2 },
  "38": { "nombre": "Sr. Julio Morales y familia", "pases": 3 },
  "39": { "nombre": "Sr. Estuardo López y familia", "pases": 5 },
  "40": { "nombre": "Sr. Gustavo Alvarado y familia", "pases": 4 },
  "41": { "nombre": "Sr. Eduardo Hernández y familia", "pases": 2 },
  "42": { "nombre": "Sr. Juan Pablo Hernández", "pases": 1 },
  "43": { "nombre": "Sra. Lourdes Hernández y familia", "pases": 4 },
  "44": { "nombre": "Sr. Samuel Hernández y familia", "pases": 4 },
  "45": { "nombre": "Sr. José Hernández", "pases": 1 },
  "46": { "nombre": "Sor Wendy Cruz", "pases": 1 },
  "47": { "nombre": "Hermanos Burn Pérez", "pases": 2 },
  "48": { "nombre": "Samantha Valentina Gallardo Ventura", "pases": 1 },
  "49": { "nombre": "André ianluca Arriaza Villatoro", "pases": 1 },
  "50": { "nombre": "Victoria Cuyuch García", "pases": 1 },
  "51": { "nombre": "", "pases": "" }, // Invitado genérico
  "52": { "nombre": "Hermanos Burn", "pases": 2 },
  "53": { "nombre": "Kevin", "pases": 1 },
  "54": { "nombre": "Nahomi", "pases": 1 },
  "55": { "nombre": "André", "pases": 2 },
  "56": { "nombre": "Mirella", "pases": 1 },
  "57": { "nombre": "Samantha", "pases": 2 },
  "58": { "nombre": "Ainhoa", "pases": 2 },
  "59": { "nombre": "Jose", "pases": 1 },
  "60": { "nombre": "Mathias", "pases": 1 },
  "61": { "nombre": "Abby", "pases": 2 },
  "62": { "nombre": "Iván", "pases": 1 },
  "63": { "nombre": "Samuel", "pases": 1 },
  "64": { "nombre": "Mateo", "pases": 1 },
  "65": { "nombre": "Diego", "pases": 1 },
  "66": { "nombre": "Sebastián", "pases": 1 },
  "67": { "nombre": "Daniela", "pases": 1 },
  "68": { "nombre": "Camila", "pases": 1 },
  "69": { "nombre": "Antonio", "pases": 1 },
  "70": { "nombre": "Baltazar", "pases": 1 },
  "71": { "nombre": "Jimena Domínguez", "pases": 2 },
  "72": { "nombre": "Jimena (Sara)", "pases": 1 },
  "73": { "nombre": "Natalia", "pases": 1 },
  "74": { "nombre": "Vittoria", "pases": 2 },
  "75": { "nombre": "Vicky", "pases": 1 },
  "76": { "nombre": "Cristhina", "pases": 1 },
  "77": { "nombre": "Joshua", "pases": 1 },
  "78": { "nombre": "Boryana", "pases": 1 },
  "79": { "nombre": "Adriana Carolina", "pases": 1 },
  "80": { "nombre": "Isa", "pases": 1 },
  "81": { "nombre": "Samantha", "pases": 1 },
  "82": { "nombre": "Valentina Montufar", "pases": 1 },
  "83": { "nombre": "Kamila Orellana", "pases": 1 },
  "84": { "nombre": "Fátima Gómez", "pases": 3 },
  "85": { "nombre": "Liz Fernandéz", "pases": 1 },
  "86": { "nombre": "Jackelin", "pases": 1 },
  "87": { "nombre": "Ximena", "pases": 1 },
  "88": { "nombre": "Dulce", "pases": 2 },
  "89": { "nombre": "Naty", "pases": 1 },
  "90": { "nombre": "Yules", "pases": 1 },
  "91": { "nombre": "Andy Pineda", "pases": 1 },
  "92": { "nombre": "Fátima (prima de Andy)", "pases": 1 },
  "93": { "nombre": "Mabel", "pases": 1 },
  "94": { "nombre": "Daniela Guidel Morales", "pases": 1 },
  "95": { "nombre": "Luchy", "pases": 1 },
  "96": { "nombre": "Valeria Crispin", "pases": 1 },
  "97": { "nombre": "Lucía", "pases": 1 },
  "98": { "nombre": "Jael Escobar", "pases": 2 },
  "99": { "nombre": "Gerardo André", "pases": 2 },
  "100": { "nombre": "Travis Douma", "pases": 5 },
  "101": { "nombre": "Katalina", "pases": 1 },
  "102": { "nombre": "Adriana Morales", "pases": 1},
  "103": { "nombre": "Licda. Claudia Conlledo", "pases": 1 },
  "104": { "nombre": "Fermin Barberena", "pases": 1 },
  "105": { "nombre": "Esposos López Oliva", "pases": 2 },
  "106": { "nombre": "Alma Cerón", "pases": 2 }
}
  